---
apiVersion: v1
kind: ServiceAccount
{{- if .Values.serviceAccounts.runner.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.serviceAccounts.runner.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
metadata:
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
  name: {{ .Values.serviceAccounts.runner.name }}
  namespace: {{ .Values.global.namespace }}
  {{- if .Values.serviceAccounts.runner.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccounts.runner.annotations | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
{{- if .Values.serviceAccounts.runner.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.serviceAccounts.runner.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
metadata:
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
  name: {{ .Values.serviceAccounts.controller.name }}
  namespace: {{ .Values.global.namespace }}
  {{- if .Values.serviceAccounts.controller.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccounts.controller.annotations | nindent 4 }}
  {{- end }}
